[project]
name = "Mini Games"
version = "1.0.0"
description = "Bogdanovych's Mini Games"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Andrii Bogdanovych", email = "a@bogdanovych.org" }
]
dependencies = [
  "flet",
  "requests"
]

[tool.flet]
org = "org.bogdanovych"
product = "MiniGames"
company = "Bogdanovych Corp."
copyright = "Copyright (C) 2025 by Andrii Bogdanovych"

[tool.flet.app]
path = "src"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"
